In [10]:
import pandas as pd
df=pd.read_csv(r"C:\Users\kathy\Downloads\annual-enterprise-survey-2023-financial-year-provisional.csv")
df

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999   
1      2023                     Level 1                99999   
2      2023                     Level 1                99999   
3      2023                     Level 1                99999   
4      2023                     Level 1                99999   
...     ...                         ...                  ...   
50980  2013                     Level 3                 ZZ11   
50981  2013                     Level 3                 ZZ11   
50982  2013                     Level 3                 ZZ11   
50983  2013                     Level 3                 ZZ11   
50984  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
50980  Food product manufacturing          Percentage           H37   
50981  Food product manufacturing          Percentage           H38   
50982  Food product manufacturing          Percentage           H39   
50983  Food product manufacturing          Percentage           H40   
50984  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
50980                                      Quick ratio       Financial ratios   
50981              Margin on sales of goods for resale       Financial ratios   
50982                                 Return on equity       Financial ratios   
50983                           Return on total assets       Financial ratios   
50984                            Liabilities structure       Financial ratios   

        Value                             Industry_code_ANZSIC06  
0      930995  ANZSIC06 divisions A-S (excluding classes K633...  
1      821630  ANZSIC06 divisions A-S (excluding classes K633...  
2       84354  ANZSIC06 divisions A-S (excluding classes K633...  
3       25010  ANZSIC06 divisions A-S (excluding classes K633...  
4      832964  ANZSIC06 divisions A-S (excluding classes K633...  
...       ...                                                ...  
50980      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50981      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50982      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50983       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50984      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[50985 rows x 10 columns]

In [9]:
df.head()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries   
1  2023                     Level 1                99999       All industries   
2  2023                     Level 1                99999       All industries   
3  2023                     Level 1                99999       All industries   
4  2023                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
import pandas as pd

# Correct file path using a raw string
file_path = r"import pandas as pd

# Correct file path using a raw string
file_path = r"C:\Users\prana\OneDrive\Desktop\abc.xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df).xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df)

In [11]:
import pandas as pd

# Correct file path using a raw string
file_path = r"C:\Users\kathy\OneDrive\문서\Book1.xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df)

Sheet1 Content:
                 Unnamed: 0                   Unnamed: 1  \
0                      Year  Industry_aggregation_NZSIOC   
1                         0                         2023   
2                         1                         2023   
3                         2                         2023   
4                         3                         2023   
5                         4                         2023   
6                       ...                          ...   
7                     50980                         2013   
8                     50981                         2013   
9                     50982                         2013   
10                    50983                         2013   
11                    50984                         2013   
12                      NaN                          NaN   
13  50985 rows × 10 columns                          NaN   

              Unnamed: 2            Unnamed: 3                  Unnamed: 4  \
0   I

In [12]:
import numpy as np

In [13]:
a=np.ones(3)

In [14]:
a

array([1., 1., 1.])

In [15]:
type(a[0])

numpy.float64

In [16]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
z.shape

(10,)

In [18]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
z=np.empty(3)
z

array([1., 1., 1.])

In [24]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])

In [26]:
z=np.array([10,20])
z

array([10, 20])